path:
  - .
  - addons
  - inc
  - includes-core
  - src
jobs: 10
extensions:
  - php
exclude:
  - vendor
  - lib/vendor
  - legacy-tests
  - .github
  - assets_wp
  - dist
  - tests
  - dev-workspace
  - images
  - languages
  - js
  - scss
