name: Deploy plugin to WordPress.org
on:
  release:
    types: [ published ]

  workflow_dispatch:
    inputs:
      tmate_enabled:
        type: boolean
        description: 'Enable "tmate" for debugging'
        required: false
        default: false

jobs:
  code-check:
    name: Check the code
    uses: ./.github/workflows/code-check.yml
    secrets: inherit

  deploy-wp-org:
    name: Deploy the new tag
    needs: [code-check]
    runs-on: ubuntu-latest
    steps:
      - name: Install linux packages
        run: |
          sudo apt-get update
          sudo apt-get install -y iproute2 subversion

      - name: Setup tmate session for Debugging, if inputs.tmate_enabled is true
        uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.tmate_enabled }}
        timeout-minutes: 10
        with:
          detached: true

      - name: Checkout code
        uses: actions/checkout@master

      - name: Create .env file
        run: |
          cp $GITHUB_WORKSPACE/.env.example $GITHUB_WORKSPACE/.env

      - name: Prepare composer
        run: |
          $GITHUB_WORKSPACE/dev-workspace/run composer validate
          $GITHUB_WORKSPACE/dev-workspace/run composer install

      - name: Show version of tools inside the dev-workspace
        run: |
          $GITHUB_WORKSPACE/dev-workspace/run composer info:versions

      - name: Build the package using ./dev-workspace
        run: |
          $GITHUB_WORKSPACE/dev-workspace/run composer build

      - name: WordPress.org plugin deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: organize-series
          BUILD_DIR: ${{ github.workspace }}/dist/organize-series

      - name: Get the plugin version number
        id: get-version
        run: |
          VERSION=$($GITHUB_WORKSPACE/dev-workspace/run pversion)
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/dist/publishpress-series-${{ steps.get-version.outputs.version }}.zip
