name: Deploy assets/readme to WordPress.org
on:
  push:
    branches:
      - 'master'

  workflow_dispatch:

jobs:
  deploy-to-trunk:
    name: Deploy assets/readme to trunk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: organize-series
          IGNORE_OTHER_FILES: true
